[tieredImporters]
eliteEnergyUsage = 4
ultraEnergyUsage = 8
megaEnergyUsage = 16
eliteSpeed = 2
ultraSpeed = 5
megaSpeed = 8
creativeSpeed = 8
eliteStackUpgradeIntegrated = false
ultraStackUpgradeIntegrated = true
megaStackUpgradeIntegrated = true
[tieredExporters]
eliteEnergyUsage = 4
ultraEnergyUsage = 8
megaEnergyUsage = 16
eliteSpeed = 2
ultraSpeed = 5
megaSpeed = 8
creativeSpeed = 8
eliteStackUpgradeIntegrated = false
ultraStackUpgradeIntegrated = true
megaStackUpgradeIntegrated = true
[tieredDestructors]
eliteEnergyUsage = 5
ultraEnergyUsage = 9
megaEnergyUsage = 17
eliteSpeed = 2
ultraSpeed = 5
megaSpeed = 8
creativeSpeed = 8
[tieredConstructors]
eliteEnergyUsage = 5
ultraEnergyUsage = 9
megaEnergyUsage = 17
eliteSpeed = 2
ultraSpeed = 5
megaSpeed = 8
creativeSpeed = 8
eliteStackUpgradeIntegrated = false
ultraStackUpgradeIntegrated = true
megaStackUpgradeIntegrated = true
[tieredDiskInterface]
eliteEnergyUsage = 7
ultraEnergyUsage = 11
megaEnergyUsage = 19
eliteSpeed = 0
ultraSpeed = 0
megaSpeed = 0
creativeSpeed = 0
eliteStackUpgradeIntegrated = false
ultraStackUpgradeIntegrated = true
megaStackUpgradeIntegrated = true
[tieredAutocrafters]
eliteEnergyUsage = 5
ultraEnergyUsage = 9
megaEnergyUsage = 17
eliteSpeed = 2
ultraSpeed = 5
megaSpeed = 8
creativeSpeed = 8
[tieredInterfaces]
eliteEnergyUsage = 5
ultraEnergyUsage = 9
megaEnergyUsage = 17
eliteTransferQuotaMultiplier = 50
ultraTransferQuotaMultiplier = 100
megaTransferQuotaMultiplier = 200
creativeTransferQuotaMultiplier = 9223372036854775807
