version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
dontCull = []
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
paintingCulling = true
leavesCullingMode = "FAST"
leavesCullingAmount = 2
includeMangroveRoots = true
endGatewayCulling = false
beaconBeamCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
customportalapi = true
cinderscapes = true
farmersdelight = true
arts_and_crafts = true
seasonsextras = true
techreborn = true
eternal_starlight = true
toneko = true
deeperdarker = true
toughasnails = true
storagedelight = true
bountifulfares = true
delicate_dyes = true
natures_spirit = true
dungeonsdelight = true
stellaris = true
mint = true
runes = true
twigs = true
minecraft = true
advanced_reborn = true
justarod = true
ends_delight = true
refinedstorage = true
spawn = true
origins = true
dye_depot = true
avaritia = true
aether = true
appledog = true
oritech = true
ftbquests = true
enchantinginfuser = true
illagerinvasion = true
excessive_building = true
spell_engine = true
