[stepCrafter]
energyUsage = 6
speedMultiplier = 14
[stepRequester]
energyUsage = 6
[stepCrafterManager]
energyUsage = 16
searchMode = "ALL"
viewType = "VISIBLE"
[stepCraftingMonitor]
energyUsage = 16
searchMode = "ALL"
viewType = "VISIBLE"
[stepRequesterManager]
energyUsage = 16
searchMode = "ALL"
viewType = "VISIBLE"
[slotUpgrade]
energyUsage = 4
